---
- name: Install Packages
  apt:
    name: "{{ server.packages }}"
    state: present
  when: server.packages is defined

- name: Configure the timezone
  timezone:
    name: "{{ server.timezone }}"

- name: Create main system user
  user:
    name: "{{ system_user }}"
    shell: /bin/bash
