framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_transaction
        failure_transport: failed

        transports:
            async: 'doctrine://default?auto_setup=false'
            failed: 'doctrine://default?queue_name=failed&auto_setup=false'

        routing:
            'Buddy\Repman\Message\Organization\SynchronizePackage': async
