security:
    encoders:
        Buddy\Repman\Entity\User:
            algorithm: auto
    providers:
        user_provider:
            entity:
                class: Buddy\Repman\Entity\User
                property: email
        organization_provider:
            id: Buddy\Repman\Security\OrganizationProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        repo:
            pattern: ^/repo/
            anonymous: false
            logout: false
            stateless: true
            provider: organization_provider
            guard:
                authenticators:
                    - Buddy\Repman\Security\TokenAuthenticator
        main:
            anonymous: lazy
            provider: user_provider
            guard:
                authenticators:
                    - Buddy\Repman\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: index
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/organization/new, roles: ROLE_USER }
         - { path: ^/organization/.+/.+, roles: ROLE_ORGANIZATION_MEMBER }
         - { path: ^/repo, roles: ROLE_ORGANIZATION }
