- name: Create project directory
  file:
    path: "{{ app_root }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0755

- name: Fetch files from git
  become_user: "{{ system_user }}"
  git:
    repo: "{{ app_git_repo }}"
    dest: "{{ app_root }}"
    version: "{{ app_git_branch }}"
    accept_hostkey: yes
    force: yes

- name: Install composer dependencies
  become_user: "{{ system_user }}"
  composer: command=install working_dir="{{ app_root }}" no_dev=yes optimize_autoloader=yes
