parameters:
    dists_dir: '%kernel.project_dir%/tests/Resources'

services:
    Buddy\Repman\Service\Downloader:
        class: Buddy\Repman\Tests\Doubles\FakeDownloader

    Buddy\Repman\Service\Cache:
        class: Buddy\Repman\Service\Cache\InMemoryCache
