---
- hosts: all
  name: Repman production setup
  become: true
  vars_files:
    - vars/public.yml
    - vars/production.yml
  roles:
#    - server
#    - postgresql
#    - nginx
#    - php
    - app.install
    - supervisor
  tasks:
    - name: Stop message consumers
      become_user: ubuntu
      supervisorctl:
        name: "{{ item }}:"
        state: stopped
      with_items:
        - "{{ app_message_consumers_name }}"

    - name: Clear doctrine metadata cache
      become_user: "{{ system_user }}"
      command: bin/console doctrine:cache:clear-metadata --env=prod --no-debug --flush
      args:
        chdir: "{{ app_root }}"

    - name: Clear symfony application cache
      become_user: "{{ system_user }}"
      file:
        path: "{{ app_root }}/symfony/cache/prod"
        state: absent

    - name: Warmup symfony application cache
      become_user: "{{ system_user }}"
      command: bin/console cache:warmup --env=prod --no-debug
      args:
        chdir: "{{ app_root }}"

    - name: Run database migrations
      become_user: "{{ system_user }}"
      command: bin/console d:m:m --no-interaction --env=prod
      args:
        chdir: "{{ app_root }}"

    - name: Start message consumers
      become_user: root
      supervisorctl:
        name: "{{ item }}:"
        state: started
      with_items:
        - "{{ app_message_consumers_name }}"
